version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    # # Disable version checks while keeping dependabot config
    # open-pull-requests-limit: 0
    # ignore:
    #   # Ignore updates to packages that start with 'aws'
    #   # Wildcards match zero or more arbitrary characters
    #   - dependency-name: "aws*"
    #   # Ignore some updates to the 'express' package
    #   - dependency-name: "express"
    #     # Ignore only new versions for 4.x and 5.x
    #     versions: ["4.x", "5.x"]
    #   # For all packages, ignore all patch updates
    #   - dependency-name: "*"
    #     update-types: ["version-update:semver-patch"]
