name: "Chromatic"
on: push
jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm i
      - name: Build tokens
        run: npm run build:tokens
      - name: Build icons
        run: npm run build:icons
      - name: Publish to Chromatic
        id: chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      - name: "Create a check run"
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.sha,
              name: "storybook",
              status: "completed",
              conclusion: "${{ steps.chromatic.conclusion }}",
              details_url: "${{ steps.chromatic.outputs.storybookUrl }}",
              output: {
                title: "Storybook",
                summary: "Storybook preview URL"
              },
            });
