name: CI

on:
  push:
    branches: [main]
  pull_request: ~
  workflow_dispatch: ~

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build:react
      - name: Linting
        run: npm run lint
      - name: Unit tests
        run: npm run test
      - name: Build storybook
        run: npm run build:storybook
